apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo-dev
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/subhankar12-spec/Devops-2026.git
    targetRevision: HEAD
    path: ArgoCD/Hands-On/nginx

    helm:
      valueFiles:
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
